// SPDX-License-Identifier: AGPL-3.0-or-later
import {msg} from '@lingui/core/macro';
export const AUTO_MOD_COPY = {
	bad_words: msg({id: 'netrcol.application_settings.automod.bad_words', message: "Bad words"}),
	repeated_text: msg({id: 'netrcol.application_settings.automod.repeated_text', message: "Repeated text"}),
	server_invites: msg({id: 'netrcol.application_settings.automod.server_invites', message: "Server invites"}),
	external_links: msg({id: 'netrcol.application_settings.automod.external_links', message: "External links"}),
	excessive_caps: msg({id: 'netrcol.application_settings.automod.excessive_caps', message: "Excessive caps"}),
	excessive_emojis: msg({id: 'netrcol.application_settings.automod.excessive_emojis', message: "Excessive emojis"}),
	excessive_spoilers: msg({id: 'netrcol.application_settings.automod.excessive_spoilers', message: "Excessive spoilers"}),
	excessive_mentions: msg({id: 'netrcol.application_settings.automod.excessive_mentions', message: "Excessive mentions"}),
	zalgo: msg({id: 'netrcol.application_settings.automod.zalgo', message: "Zalgo text"}),
	anti_spam: msg({id: 'netrcol.application_settings.automod.anti_spam', message: "Anti-spam"}),
	character_limit: msg({id: 'netrcol.application_settings.automod.character_limit', message: "Character limit"}),
	media_spam: msg({id: 'netrcol.application_settings.automod.media_spam', message: "Media spam"}),
	anti_raid: msg({id: 'netrcol.application_settings.automod.anti_raid', message: "Anti Raid"}),
	anti_nuke: msg({id: 'netrcol.application_settings.automod.anti_nuke', message: "Anti Nuke"}),
	observe: msg({id: 'netrcol.application_settings.automod.observe', message: "Log only"}),
	warn: msg({id: 'netrcol.application_settings.automod.warn', message: "Warn member"}),
	lockdown: msg({id: 'netrcol.application_settings.automod.lockdown', message: "Lockdown"}),
	ignoreBots: msg({id: 'netrcol.application_settings.automod.ignoreBots', message: "Ignore bots"}),
	window: msg({id: 'netrcol.application_settings.automod.window', message: "Time window (s)"}),
	minimumLength: msg({id: 'netrcol.application_settings.automod.minimumLength', message: "Minimum letters"}),
	domains: msg({id: 'netrcol.application_settings.automod.domains', message: "Allowed domains"}),
	loadError: msg({id: 'netrcol.application_settings.automod.loadError', message: "Could not load AutoMod. Try again."}),
	saveError: msg({id: 'netrcol.application_settings.automod.saveError', message: "Check the rules and try saving again."}),
	exemptChannels: msg({id: 'netrcol.application_settings.automod.exemptChannels', message: "Exempt channels"}),
	configUpdated: msg({id: 'netrcol.application_settings.automod.configUpdated', message: "AutoMod settings updated"}),
	scope: msg({id: 'netrcol.application_settings.automod.scope', message: "Messages are checked after sending. The owner and system messages are exempt."}),
	sharedPermissions: msg({id: 'netrcol.application_settings.automod.sharedPermissions', message: "Shared permissions"}),
	inherited: msg({id: 'netrcol.application_settings.automod.inherited', message: "This rule uses the user, role, channel and category scope set on the AutoMod page."}),
	separate: msg({id: 'netrcol.application_settings.automod.separate', message: "Use separate permissions for this rule"}),
	allExcept: msg({id: 'netrcol.application_settings.automod.allExcept', message: "Apply to all except selected"}),
	onlySelected: msg({id: 'netrcol.application_settings.automod.onlySelected', message: "Apply only to selected"}),
	userPriority: msg({id: 'netrcol.application_settings.automod.userPriority', message: "An explicit user selection takes priority over roles. Channel and category restrictions still apply."}),
	userId: msg({id: 'netrcol.application_settings.automod.userId', message: "User ID"}),
	discard: msg({id: 'netrcol.application_settings.automod.discard', message: "Discard"}),
	saveClose: msg({id: 'netrcol.application_settings.automod.saveClose', message: "Save & Close"}),
	additional: msg({id: 'netrcol.application_settings.automod.additional', message: "Additional settings"}),
	wordHint: msg({id: 'netrcol.application_settings.automod.wordHint', message: "Press Enter or type a comma after each word. Up to 200 entries per list, 100 characters each."}),
	exactWords: msg({id: 'netrcol.application_settings.automod.exactWords', message: "Bad words (exact match)"}),
	partialWords: msg({id: 'netrcol.application_settings.automod.partialWords', message: "Bad words (match any part)"}),
	addWord: msg({id: 'netrcol.application_settings.automod.addWord', message: "Add a word…"}),
	howWorks: msg({id: 'netrcol.application_settings.automod.howWorks', message: "How does it work?"}),
	matchingHint: msg({id: 'netrcol.application_settings.automod.matchingHint', message: "Matching ignores letter case. Exact matching checks whole words; partial matching also finds text inside a word."}),
	permissions: msg({id: 'netrcol.application_settings.automod.permissions', message: "Permissions"}),
	users: msg({id: 'netrcol.application_settings.automod.users', message: "Users"}),
	roles: msg({id: 'netrcol.application_settings.automod.roles', message: "Roles"}),
	channels: msg({id: 'netrcol.application_settings.automod.channels', message: "Channels"}),
	categories: msg({id: 'netrcol.application_settings.automod.categories', message: "Categories"}),
	add: msg({id: 'netrcol.application_settings.automod.add', message: "Add"}),
	remove: msg({id: 'netrcol.application_settings.automod.remove', message: "Remove"}),
	back: msg({id: 'netrcol.application_settings.automod.back', message: "Back"}),
	repeatThreshold: msg({id: 'netrcol.application_settings.automod.repeatThreshold', message: "Repeated messages"}),
	repeatCountHint: msg({id: 'netrcol.application_settings.automod.repeatCountHint', message: "Trigger when the same member sends identical text this many times within the time window."}),
	repeatWindowHint: msg({id: 'netrcol.application_settings.automod.repeatWindowHint', message: "Counts messages across channels in this rule's scope. Case, spacing and invisible characters are normalized. Message edits do not count as new messages."}),
	linkWhitelist: msg({id: 'netrcol.application_settings.automod.linkWhitelist', message: "Link whitelist"}),
	linkHint: msg({id: 'netrcol.application_settings.automod.linkHint', message: "Enter a URL prefix and press Enter or comma. Matching links bypass both invite and external link filters. Matching is case-sensitive and includes the scheme and path."}),
	linkInvalid: msg({id: 'netrcol.application_settings.automod.linkInvalid', message: "Enter an HTTP or HTTPS URL prefix without spaces or credentials. Up to 100 entries, 2048 characters each."}),
	capsMinimumCharacters: msg({id: 'netrcol.application_settings.automod.capsMinimumCharacters', message: "Minimum characters"}),
	capsMaximumPercentage: msg({id: 'netrcol.application_settings.automod.capsMaximumPercentage', message: "Maximum uppercase (%)"}),
	capsHint: msg({id: 'netrcol.application_settings.automod.capsHint', message: "Only letters with uppercase and lowercase forms count toward the minimum and percentage. The rule triggers only when the percentage exceeds the limit."}),
	emojiLimit: msg({id: 'netrcol.application_settings.automod.emojiLimit', message: "Emoji limit"}),
	emojiLimitHint: msg({id: 'netrcol.application_settings.automod.emojiLimitHint', message: "The rule triggers when the emoji count exceeds this limit. Unicode and custom emojis are counted; joined emoji sequences count as one."}),
	spoilerLimit: msg({id: 'netrcol.application_settings.automod.spoilerLimit', message: "Spoiler tags limit"}),
	spoilerLimitHint: msg({id: 'netrcol.application_settings.automod.spoilerLimitHint', message: "Each section enclosed by || markers counts as one, including multiline sections. The rule triggers only when the count exceeds this limit."}),
	mentionLimit: msg({id: 'netrcol.application_settings.automod.mentionLimit', message: "Mentions limit"}),
	mentionLimitHint: msg({id: 'netrcol.application_settings.automod.mentionLimitHint', message: "Counts distinct user and role mention tags, @everyone and @here. Repeating the same tag counts once. The rule triggers only when the count exceeds this limit."}),
	messageLimit: msg({id: 'netrcol.application_settings.automod.messageLimit', message: "Message limit"}),
	spamHint: msg({id: 'netrcol.application_settings.automod.spamHint', message: "Counts new messages from the same member in this rule’s channels. The rule triggers when the limit is reached within the time window; edits do not count."}),
	maximumCharacters: msg({id: 'netrcol.application_settings.automod.maximumCharacters', message: "Maximum characters"}),
	characterLimitHint: msg({id: 'netrcol.application_settings.automod.characterLimitHint', message: "Counts message text, including spaces and line breaks. Combined emoji or accented characters can count as several characters. The rule triggers only when this limit is exceeded."}),
	mediaLimit: msg({id: 'netrcol.application_settings.automod.mediaLimit', message: "Media limit"}),
	mediaSpamHint: msg({id: 'netrcol.application_settings.automod.mediaSpamHint', message: "Counts attachments and stickers sent by the same member in this rule’s channels. The rule triggers when the total reaches the limit within the time window; edits, links and emoji do not count."}),
	joinLimit: msg({id: 'netrcol.application_settings.automod.joinLimit', message: "Join limit"}),
	actionLimit: msg({id: 'netrcol.application_settings.automod.actionLimit', message: "Action limit"}),
	newAccountDays: msg({id: 'netrcol.application_settings.automod.newAccountDays', message: "New account days"}),
	raidHint: msg({id: 'netrcol.application_settings.automod.raidHint', message: "Counts joins from accounts younger than this many days. Use 0 to count all accounts. Reaching the join limit within the time window triggers the selected action."}),
	nukeHint: msg({id: 'netrcol.application_settings.automod.nukeHint', message: "Counts potentially destructive administrative actions by the same member, including community, channel, role, ban, kick, bot and webhook changes."}),
	logOnly: msg({id: 'netrcol.application_settings.automod.logOnly', message: "Start in log-only mode"}),
	logOnlyHint: msg({id: 'netrcol.application_settings.automod.logOnlyHint', message: "Records matches without restricting the member. Turn off to use the action selected on the AutoMod page. Disabled rules stay disabled."}),
	protectionHint: msg({id: 'netrcol.application_settings.automod.protectionHint', message: "These rules work independently of the Security module when AutoMod and the rule are enabled and saved. Lockdown uses the duration set on the AutoMod page."}),
	disabled: msg({id: 'netrcol.application_settings.automod.disabled', message: "Disabled"}),
	delete: msg({id: 'netrcol.application_settings.automod.delete', message: "Delete message"}),
	timeout: msg({id: 'netrcol.application_settings.automod.timeout', message: "Timeout"}),
	delete_warn: msg({id: 'netrcol.application_settings.automod.delete_warn', message: "Delete message + Warn member"}),
	delete_timeout: msg({id: 'netrcol.application_settings.automod.delete_timeout', message: "Delete message + Timeout"}),
};
