// SPDX-License-Identifier: AGPL-3.0-or-later
import {msg} from '@lingui/core/macro';
export const EVENT_LOG_LABELS = {
	"member_join": msg({id: 'netrcol.application_settings.logCatalog.member_join', message: "Member joined"}),
	"member_leave": msg({id: 'netrcol.application_settings.logCatalog.member_leave', message: "Member left"}),
	"bot_add": msg({id: 'netrcol.application_settings.logCatalog.bot_add', message: "Bot added"}),
	"member_update": msg({id: 'netrcol.application_settings.logCatalog.member_update', message: "Community profile changed"}),
	"user_profile_update": msg({id: 'netrcol.application_settings.logCatalog.user_profile_update', message: "Public user profile changed"}),
	"member_kick": msg({id: 'netrcol.application_settings.logCatalog.member_kick', message: "Member kicked"}),
	"member_prune": msg({id: 'netrcol.application_settings.logCatalog.member_prune', message: "Members pruned"}),
	"member_ban_add": msg({id: 'netrcol.application_settings.logCatalog.member_ban_add', message: "Member banned"}),
	"member_ban_remove": msg({id: 'netrcol.application_settings.logCatalog.member_ban_remove', message: "Member unbanned"}),
	"member_timeout": msg({id: 'netrcol.application_settings.logCatalog.member_timeout', message: "Member timeout changed"}),
	"member_server_mute": msg({id: 'netrcol.application_settings.logCatalog.member_server_mute', message: "Server mute changed"}),
	"member_server_deaf": msg({id: 'netrcol.application_settings.logCatalog.member_server_deaf', message: "Server deafen changed"}),
	"member_move": msg({id: 'netrcol.application_settings.logCatalog.member_move', message: "Member moved by a moderator"}),
	"member_disconnect": msg({id: 'netrcol.application_settings.logCatalog.member_disconnect', message: "Member disconnected by a moderator"}),
	"message_create": msg({id: 'netrcol.application_settings.logCatalog.message_create', message: "Message created"}),
	"message_update": msg({id: 'netrcol.application_settings.logCatalog.message_update', message: "Message edited"}),
	"message_delete": msg({id: 'netrcol.application_settings.logCatalog.message_delete', message: "Message deleted"}),
	"message_bulk_delete": msg({id: 'netrcol.application_settings.logCatalog.message_bulk_delete', message: "Messages bulk deleted"}),
	"message_pin": msg({id: 'netrcol.application_settings.logCatalog.message_pin', message: "Message pinned"}),
	"message_unpin": msg({id: 'netrcol.application_settings.logCatalog.message_unpin', message: "Message unpinned"}),
	"message_publish": msg({id: 'netrcol.application_settings.logCatalog.message_publish', message: "Announcement published"}),
	"reaction_add": msg({id: 'netrcol.application_settings.logCatalog.reaction_add', message: "Reaction added"}),
	"reaction_remove": msg({id: 'netrcol.application_settings.logCatalog.reaction_remove', message: "Reaction removed"}),
	"reaction_clear": msg({id: 'netrcol.application_settings.logCatalog.reaction_clear', message: "All reactions removed"}),
	"reaction_clear_emoji": msg({id: 'netrcol.application_settings.logCatalog.reaction_clear_emoji', message: "Emoji reactions removed"}),
	"channel_create": msg({id: 'netrcol.application_settings.logCatalog.channel_create', message: "Channel created"}),
	"channel_update": msg({id: 'netrcol.application_settings.logCatalog.channel_update', message: "Channel changed"}),
	"channel_delete": msg({id: 'netrcol.application_settings.logCatalog.channel_delete', message: "Channel deleted"}),
	"channel_overwrite_create": msg({id: 'netrcol.application_settings.logCatalog.channel_overwrite_create', message: "Channel permission override added"}),
	"channel_overwrite_update": msg({id: 'netrcol.application_settings.logCatalog.channel_overwrite_update', message: "Channel permission override changed"}),
	"channel_overwrite_delete": msg({id: 'netrcol.application_settings.logCatalog.channel_overwrite_delete', message: "Channel permission override removed"}),
	"role_create": msg({id: 'netrcol.application_settings.logCatalog.role_create', message: "Role created"}),
	"role_update": msg({id: 'netrcol.application_settings.logCatalog.role_update', message: "Role changed"}),
	"role_delete": msg({id: 'netrcol.application_settings.logCatalog.role_delete', message: "Role deleted"}),
	"member_role_update": msg({id: 'netrcol.application_settings.logCatalog.member_role_update', message: "Member roles changed"}),
	"invite_create": msg({id: 'netrcol.application_settings.logCatalog.invite_create', message: "Invite created"}),
	"invite_update": msg({id: 'netrcol.application_settings.logCatalog.invite_update', message: "Invite changed"}),
	"invite_delete": msg({id: 'netrcol.application_settings.logCatalog.invite_delete', message: "Invite deleted"}),
	"invite_use": msg({id: 'netrcol.application_settings.logCatalog.invite_use', message: "Invite used"}),
	"webhook_create": msg({id: 'netrcol.application_settings.logCatalog.webhook_create', message: "Webhook created"}),
	"webhook_update": msg({id: 'netrcol.application_settings.logCatalog.webhook_update', message: "Webhook changed"}),
	"webhook_delete": msg({id: 'netrcol.application_settings.logCatalog.webhook_delete', message: "Webhook deleted"}),
	"emoji_create": msg({id: 'netrcol.application_settings.logCatalog.emoji_create', message: "Emoji created"}),
	"emoji_update": msg({id: 'netrcol.application_settings.logCatalog.emoji_update', message: "Emoji changed"}),
	"emoji_delete": msg({id: 'netrcol.application_settings.logCatalog.emoji_delete', message: "Emoji deleted"}),
	"sticker_create": msg({id: 'netrcol.application_settings.logCatalog.sticker_create', message: "Sticker created"}),
	"sticker_update": msg({id: 'netrcol.application_settings.logCatalog.sticker_update', message: "Sticker changed"}),
	"sticker_delete": msg({id: 'netrcol.application_settings.logCatalog.sticker_delete', message: "Sticker deleted"}),
	"guild_update": msg({id: 'netrcol.application_settings.logCatalog.guild_update', message: "Community settings changed"}),
	"voice_join": msg({id: 'netrcol.application_settings.logCatalog.voice_join', message: "Voice channel joined"}),
	"voice_leave": msg({id: 'netrcol.application_settings.logCatalog.voice_leave', message: "Voice channel left"}),
	"voice_move": msg({id: 'netrcol.application_settings.logCatalog.voice_move', message: "Voice channel changed"}),
	"voice_self_mute": msg({id: 'netrcol.application_settings.logCatalog.voice_self_mute', message: "Self mute changed"}),
	"voice_self_deaf": msg({id: 'netrcol.application_settings.logCatalog.voice_self_deaf', message: "Self deafen changed"}),
	"voice_video": msg({id: 'netrcol.application_settings.logCatalog.voice_video', message: "Camera state changed"}),
	"voice_stream": msg({id: 'netrcol.application_settings.logCatalog.voice_stream', message: "Screen sharing changed"}),
	"voice_suppress": msg({id: 'netrcol.application_settings.logCatalog.voice_suppress', message: "Voice suppression changed"}),
	"entrance_sound_play": msg({id: 'netrcol.application_settings.logCatalog.entrance_sound_play', message: "Entrance sound played"}),
	"presence_status": msg({id: 'netrcol.application_settings.logCatalog.presence_status', message: "Visible presence changed"}),
	"presence_custom_status": msg({id: 'netrcol.application_settings.logCatalog.presence_custom_status', message: "Custom status changed"}),
	"category_members": msg({id: 'netrcol.application_settings.logCatalog.category_members', message: "Membership and profile"}),
	"category_moderation": msg({id: 'netrcol.application_settings.logCatalog.category_moderation', message: "Moderation"}),
	"category_messages": msg({id: 'netrcol.application_settings.logCatalog.category_messages', message: "Messages"}),
	"category_reactions": msg({id: 'netrcol.application_settings.logCatalog.category_reactions', message: "Reactions"}),
	"category_channels": msg({id: 'netrcol.application_settings.logCatalog.category_channels', message: "Channels and Categories"}),
	"category_permissions": msg({id: 'netrcol.application_settings.logCatalog.category_permissions', message: "Channel permissions"}),
	"category_roles": msg({id: 'netrcol.application_settings.logCatalog.category_roles', message: "Roles"}),
	"category_invites": msg({id: 'netrcol.application_settings.logCatalog.category_invites', message: "Invites"}),
	"category_integrations": msg({id: 'netrcol.application_settings.logCatalog.category_integrations', message: "Webhooks and expressions"}),
	"category_guild": msg({id: 'netrcol.application_settings.logCatalog.category_guild', message: "Community"}),
	"category_voice": msg({id: 'netrcol.application_settings.logCatalog.category_voice', message: "Voice and visible status"}),
	"search": msg({id: 'netrcol.application_settings.logCatalog.search', message: "Search"}),
	"selectAll": msg({id: 'netrcol.application_settings.logCatalog.selectAll', message: "Select all"}),
	"clear": msg({id: 'netrcol.application_settings.logCatalog.clear', message: "Clear selection"}),
	"inherit": msg({id: 'netrcol.application_settings.logCatalog.inherit', message: "Inherit"}),
	"defaultChannel": msg({id: 'netrcol.application_settings.logCatalog.defaultChannel', message: "Default Channel"}),
	"capture": msg({id: 'netrcol.application_settings.logCatalog.capture', message: "Log message text"}),
	"preview": msg({id: 'netrcol.application_settings.logCatalog.preview', message: "Preview"}),
	"test": msg({id: 'netrcol.application_settings.logCatalog.test', message: "Send test message"}),
	"time": msg({id: 'netrcol.application_settings.logCatalog.time', message: "Time"}),
	"actor": msg({id: 'netrcol.application_settings.logCatalog.actor', message: "Actor"}),
	"target": msg({id: 'netrcol.application_settings.logCatalog.target', message: "Target"}),
	"source": msg({id: 'netrcol.application_settings.logCatalog.source', message: "Channel"}),
	"reason": msg({id: 'netrcol.application_settings.logCatalog.reason', message: "Reason"}),
	"unknown": msg({id: 'netrcol.application_settings.logCatalog.unknown', message: "Unknown"}),
	"before": msg({id: 'netrcol.application_settings.logCatalog.before', message: "Before"}),
	"after": msg({id: 'netrcol.application_settings.logCatalog.after', message: "After"}),
	"changes": msg({id: 'netrcol.application_settings.logCatalog.changes', message: "Settings Edit"}),
	"attachments": msg({id: 'netrcol.application_settings.logCatalog.attachments', message: "Attachments"}),
	"count": msg({id: 'netrcol.application_settings.logCatalog.count', message: "Messages"}),
	"fileType": msg({id: 'netrcol.application_settings.logCatalog.fileType', message: "File format"}),
	"size": msg({id: 'netrcol.application_settings.logCatalog.size', message: "Size"}),
	"enabled": msg({id: 'netrcol.application_settings.logCatalog.enabled', message: "Enabled"}),
	"disabled": msg({id: 'netrcol.application_settings.logCatalog.disabled', message: "Disabled"}),
	"system": msg({id: 'netrcol.application_settings.logCatalog.system', message: "System"}),
	"testMark": msg({id: 'netrcol.application_settings.logCatalog.testMark', message: "Test message"}),
	"logTitle": msg({id: 'netrcol.application_settings.logCatalog.logTitle', message: "Event logs"}),
	"none": msg({id: 'netrcol.application_settings.logCatalog.none', message: "None"}),
	"message": msg({id: 'netrcol.application_settings.logCatalog.message', message: "Message"}),
	"channel_text": msg({id: 'netrcol.application_settings.logCatalog.channel_text', message: "Text channel"}),
	"channel_voice": msg({id: 'netrcol.application_settings.logCatalog.channel_voice', message: "Voice channel"}),
	"channel_category": msg({id: 'netrcol.application_settings.logCatalog.channel_category', message: "Category"}),
	"channel_announcement": msg({id: 'netrcol.application_settings.logCatalog.channel_announcement', message: "Announcement channel"}),
	"channel_link": msg({id: 'netrcol.application_settings.logCatalog.channel_link', message: "Channel Link"}),
	"permission_ADMINISTRATOR": msg({id: 'netrcol.application_settings.logCatalog.permission_ADMINISTRATOR', message: "Administrator"}),
	"permission_VIEW_AUDIT_LOG": msg({id: 'netrcol.application_settings.logCatalog.permission_VIEW_AUDIT_LOG', message: "View activity log"}),
	"permission_MANAGE_GUILD": msg({id: 'netrcol.application_settings.logCatalog.permission_MANAGE_GUILD', message: "Manage community"}),
	"permission_MANAGE_ROLES": msg({id: 'netrcol.application_settings.logCatalog.permission_MANAGE_ROLES', message: "Manage roles"}),
	"permission_MANAGE_CHANNELS": msg({id: 'netrcol.application_settings.logCatalog.permission_MANAGE_CHANNELS', message: "Manage channels"}),
	"permission_KICK_MEMBERS": msg({id: 'netrcol.application_settings.logCatalog.permission_KICK_MEMBERS', message: "Kick members"}),
	"permission_BAN_MEMBERS": msg({id: 'netrcol.application_settings.logCatalog.permission_BAN_MEMBERS', message: "Ban members"}),
	"permission_CREATE_INSTANT_INVITE": msg({id: 'netrcol.application_settings.logCatalog.permission_CREATE_INSTANT_INVITE', message: "Create invite links"}),
	"permission_CHANGE_NICKNAME": msg({id: 'netrcol.application_settings.logCatalog.permission_CHANGE_NICKNAME', message: "Change own nickname"}),
	"permission_MANAGE_NICKNAMES": msg({id: 'netrcol.application_settings.logCatalog.permission_MANAGE_NICKNAMES', message: "Manage nicknames"}),
	"permission_CREATE_EXPRESSIONS": msg({id: 'netrcol.application_settings.logCatalog.permission_CREATE_EXPRESSIONS', message: "Create emoji & stickers"}),
	"permission_MANAGE_EXPRESSIONS": msg({id: 'netrcol.application_settings.logCatalog.permission_MANAGE_EXPRESSIONS', message: "Manage emoji & stickers"}),
	"permission_MANAGE_WEBHOOKS": msg({id: 'netrcol.application_settings.logCatalog.permission_MANAGE_WEBHOOKS', message: "Manage webhooks"}),
	"permission_SEND_MESSAGES": msg({id: 'netrcol.application_settings.logCatalog.permission_SEND_MESSAGES', message: "Send messages"}),
	"permission_SEND_TTS_MESSAGES": msg({id: 'netrcol.application_settings.logCatalog.permission_SEND_TTS_MESSAGES', message: "Send TTS messages"}),
	"permission_MANAGE_MESSAGES": msg({id: 'netrcol.application_settings.logCatalog.permission_MANAGE_MESSAGES', message: "Manage messages"}),
	"permission_PIN_MESSAGES": msg({id: 'netrcol.application_settings.logCatalog.permission_PIN_MESSAGES', message: "Pin messages"}),
	"permission_EMBED_LINKS": msg({id: 'netrcol.application_settings.logCatalog.permission_EMBED_LINKS', message: "Embed links"}),
	"permission_ATTACH_FILES": msg({id: 'netrcol.application_settings.logCatalog.permission_ATTACH_FILES', message: "Attach files"}),
	"permission_READ_MESSAGE_HISTORY": msg({id: 'netrcol.application_settings.logCatalog.permission_READ_MESSAGE_HISTORY', message: "Read message history"}),
	"permission_USE_EXTERNAL_EMOJIS": msg({id: 'netrcol.application_settings.logCatalog.permission_USE_EXTERNAL_EMOJIS', message: "Use external emoji"}),
	"permission_USE_EXTERNAL_STICKERS": msg({id: 'netrcol.application_settings.logCatalog.permission_USE_EXTERNAL_STICKERS', message: "Use external stickers"}),
	"permission_ADD_REACTIONS": msg({id: 'netrcol.application_settings.logCatalog.permission_ADD_REACTIONS', message: "Add reactions"}),
	"permission_BYPASS_SLOWMODE": msg({id: 'netrcol.application_settings.logCatalog.permission_BYPASS_SLOWMODE', message: "Bypass slowmode"}),
	"permission_MODERATE_MEMBERS": msg({id: 'netrcol.application_settings.logCatalog.permission_MODERATE_MEMBERS', message: "Time out members"}),
	"permission_VIEW_CHANNEL": msg({id: 'netrcol.application_settings.logCatalog.permission_VIEW_CHANNEL', message: "View channel"}),
	"permission_VIEW_CHANNEL_MEMBERS": msg({id: 'netrcol.application_settings.logCatalog.permission_VIEW_CHANNEL_MEMBERS', message: "View channel members"}),
	"permission_CONNECT": msg({id: 'netrcol.application_settings.logCatalog.permission_CONNECT', message: "Connect to voice"}),
	"permission_SPEAK": msg({id: 'netrcol.application_settings.logCatalog.permission_SPEAK', message: "Speak"}),
	"permission_STREAM": msg({id: 'netrcol.application_settings.logCatalog.permission_STREAM', message: "Stream video"}),
	"permission_USE_VAD": msg({id: 'netrcol.application_settings.logCatalog.permission_USE_VAD', message: "Use voice activity"}),
	"permission_PRIORITY_SPEAKER": msg({id: 'netrcol.application_settings.logCatalog.permission_PRIORITY_SPEAKER', message: "Priority speaker"}),
	"permission_MUTE_MEMBERS": msg({id: 'netrcol.application_settings.logCatalog.permission_MUTE_MEMBERS', message: "Mute members"}),
	"permission_DEAFEN_MEMBERS": msg({id: 'netrcol.application_settings.logCatalog.permission_DEAFEN_MEMBERS', message: "Deafen members"}),
	"permission_MOVE_MEMBERS": msg({id: 'netrcol.application_settings.logCatalog.permission_MOVE_MEMBERS', message: "Move members"}),
	"permission_UPDATE_RTC_REGION": msg({id: 'netrcol.application_settings.logCatalog.permission_UPDATE_RTC_REGION', message: "Set voice region"}),
	"permission_MENTION_EVERYONE": msg({id: 'netrcol.application_settings.logCatalog.permission_MENTION_EVERYONE', message: "Use {everyoneMention}/{hereMention} and {rolesMention}"}),
	"destination": msg({id: 'netrcol.application_settings.logCatalog.destination', message: "Log channel"}),
	"status_online": msg({id: 'netrcol.application_settings.logCatalog.status_online', message: "Online"}),
	"status_idle": msg({id: 'netrcol.application_settings.logCatalog.status_idle', message: "Idle"}),
	"status_dnd": msg({id: 'netrcol.application_settings.logCatalog.status_dnd', message: "Do not disturb"}),
	"status_offline": msg({id: 'netrcol.application_settings.logCatalog.status_offline', message: "Offline"}),
	"field_name": msg({id: 'netrcol.application_settings.logCatalog.field_name', message: "Name"}),
	"field_nick": msg({id: 'netrcol.application_settings.logCatalog.field_nick', message: "Nickname"}),
	"field_username": msg({id: 'netrcol.application_settings.logCatalog.field_username', message: "Username"}),
	"field_discriminator": msg({id: 'netrcol.application_settings.logCatalog.field_discriminator', message: "Discriminator"}),
	"field_global_name": msg({id: 'netrcol.application_settings.logCatalog.field_global_name', message: "Display name"}),
	"field_avatar_hash": msg({id: 'netrcol.application_settings.logCatalog.field_avatar_hash', message: "Avatar"}),
	"field_banner_hash": msg({id: 'netrcol.application_settings.logCatalog.field_banner_hash', message: "Banner"}),
	"field_bio": msg({id: 'netrcol.application_settings.logCatalog.field_bio', message: "Bio"}),
	"field_pronouns": msg({id: 'netrcol.application_settings.logCatalog.field_pronouns', message: "Pronouns"}),
	"field_accent_color": msg({id: 'netrcol.application_settings.logCatalog.field_accent_color', message: "Accent color"}),
	"field_roles": msg({id: 'netrcol.application_settings.logCatalog.field_roles', message: "Roles"}),
	"field_$add": msg({id: 'netrcol.application_settings.logCatalog.field_$add', message: "Add"}),
	"field_$remove": msg({id: 'netrcol.application_settings.logCatalog.field_$remove', message: "Remove"}),
	"field_permissions": msg({id: 'netrcol.application_settings.logCatalog.field_permissions', message: "Permissions"}),
	"field_color": msg({id: 'netrcol.application_settings.logCatalog.field_color', message: "Color"}),
	"field_hoist": msg({id: 'netrcol.application_settings.logCatalog.field_hoist', message: "Display role members separately from online members"}),
	"field_mentionable": msg({id: 'netrcol.application_settings.logCatalog.field_mentionable', message: "Allow anyone to mention this role"}),
	"field_position": msg({id: 'netrcol.application_settings.logCatalog.field_position', message: "Position"}),
	"field_hoist_position": msg({id: 'netrcol.application_settings.logCatalog.field_hoist_position', message: "Position"}),
	"field_icon": msg({id: 'netrcol.application_settings.logCatalog.field_icon', message: "Icon"}),
	"field_icon_hash": msg({id: 'netrcol.application_settings.logCatalog.field_icon_hash', message: "Icon"}),
	"field_unicode_emoji": msg({id: 'netrcol.application_settings.logCatalog.field_unicode_emoji', message: "Emoji"}),
	"field_topic": msg({id: 'netrcol.application_settings.logCatalog.field_topic', message: "Topic"}),
	"field_type": msg({id: 'netrcol.application_settings.logCatalog.field_type', message: "Channel type"}),
	"field_parent_id": msg({id: 'netrcol.application_settings.logCatalog.field_parent_id', message: "Category"}),
	"field_nsfw": msg({id: 'netrcol.application_settings.logCatalog.field_nsfw', message: "Mature content"}),
	"field_rate_limit_per_user": msg({id: 'netrcol.application_settings.logCatalog.field_rate_limit_per_user', message: "Slowmode"}),
	"field_bitrate": msg({id: 'netrcol.application_settings.logCatalog.field_bitrate', message: "Bitrate"}),
	"field_user_limit": msg({id: 'netrcol.application_settings.logCatalog.field_user_limit', message: "User limit"}),
	"field_voice_connection_limit": msg({id: 'netrcol.application_settings.logCatalog.field_voice_connection_limit', message: "User limit"}),
	"field_rtc_region": msg({id: 'netrcol.application_settings.logCatalog.field_rtc_region', message: "Region"}),
	"field_permission_overwrites": msg({id: 'netrcol.application_settings.logCatalog.field_permission_overwrites', message: "Permissions"}),
	"field_allow": msg({id: 'netrcol.application_settings.logCatalog.field_allow', message: "Allow"}),
	"field_deny": msg({id: 'netrcol.application_settings.logCatalog.field_deny', message: "Deny"}),
	"field_id": msg({id: 'netrcol.application_settings.logCatalog.field_id', message: "ID"}),
	"field_owner_id": msg({id: 'netrcol.application_settings.logCatalog.field_owner_id', message: "Owner"}),
	"field_verification_level": msg({id: 'netrcol.application_settings.logCatalog.field_verification_level', message: "Verification level"}),
	"field_default_message_notifications": msg({id: 'netrcol.application_settings.logCatalog.field_default_message_notifications', message: "Notification settings"}),
	"field_explicit_content_filter": msg({id: 'netrcol.application_settings.logCatalog.field_explicit_content_filter', message: "Content filter"}),
	"field_afk_channel_id": msg({id: 'netrcol.application_settings.logCatalog.field_afk_channel_id', message: "AFK channel"}),
	"field_afk_timeout": msg({id: 'netrcol.application_settings.logCatalog.field_afk_timeout', message: "AFK timeout"}),
	"field_system_channel_id": msg({id: 'netrcol.application_settings.logCatalog.field_system_channel_id', message: "System messages channel"}),
	"field_system_channel_flags": msg({id: 'netrcol.application_settings.logCatalog.field_system_channel_flags', message: "System messages"}),
	"field_splash_hash": msg({id: 'netrcol.application_settings.logCatalog.field_splash_hash', message: "Invite background"}),
	"field_embed_splash_hash": msg({id: 'netrcol.application_settings.logCatalog.field_embed_splash_hash', message: "Invite background"}),
	"field_description": msg({id: 'netrcol.application_settings.logCatalog.field_description', message: "Description"}),
	"field_features": msg({id: 'netrcol.application_settings.logCatalog.field_features', message: "Features"}),
	"field_vanity_url_code": msg({id: 'netrcol.application_settings.logCatalog.field_vanity_url_code', message: "Custom invite link"}),
	"field_disabled_operations": msg({id: 'netrcol.application_settings.logCatalog.field_disabled_operations', message: "Disabled"}),
	"field_max_age": msg({id: 'netrcol.application_settings.logCatalog.field_max_age', message: "Expires after"}),
	"field_max_uses": msg({id: 'netrcol.application_settings.logCatalog.field_max_uses', message: "Max uses"}),
	"field_uses": msg({id: 'netrcol.application_settings.logCatalog.field_uses', message: "Uses"}),
	"field_temporary": msg({id: 'netrcol.application_settings.logCatalog.field_temporary', message: "Temporary membership"}),
	"field_channel_id": msg({id: 'netrcol.application_settings.logCatalog.field_channel_id', message: "Channel"}),
	"field_inviter_id": msg({id: 'netrcol.application_settings.logCatalog.field_inviter_id', message: "User"}),
	"field_creator_id": msg({id: 'netrcol.application_settings.logCatalog.field_creator_id', message: "User"}),
	"field_guild_id": msg({id: 'netrcol.application_settings.logCatalog.field_guild_id', message: "Community"}),
	"field_available": msg({id: 'netrcol.application_settings.logCatalog.field_available', message: "Available"}),
	"field_mute": msg({id: 'netrcol.application_settings.logCatalog.field_mute', message: "Mute"}),
	"field_deaf": msg({id: 'netrcol.application_settings.logCatalog.field_deaf', message: "Deafen"}),
	"field_communication_disabled_until": msg({id: 'netrcol.application_settings.logCatalog.field_communication_disabled_until', message: "Timeout"}),
	"field_url": msg({id: 'netrcol.application_settings.logCatalog.field_url', message: "URL"}),
	"field_format_type": msg({id: 'netrcol.application_settings.logCatalog.field_format_type', message: "File format"}),
	"field_tags": msg({id: 'netrcol.application_settings.logCatalog.field_tags', message: "Tags"}),
	"field_flags": msg({id: 'netrcol.application_settings.logCatalog.field_flags', message: "Flags"}),
	"field_animated": msg({id: 'netrcol.application_settings.logCatalog.field_animated', message: "Animated"}),
	"field_content": msg({id: 'netrcol.application_settings.logCatalog.field_content', message: "Message"}),
	"field_attachments": msg({id: 'netrcol.application_settings.logCatalog.field_attachments', message: "Attachments"}),
	"field_embeds": msg({id: 'netrcol.application_settings.logCatalog.field_embeds', message: "Embeds"}),
	"field_sticker_items": msg({id: 'netrcol.application_settings.logCatalog.field_sticker_items', message: "Stickers"}),
	"field_status": msg({id: 'netrcol.application_settings.logCatalog.field_status', message: "Status"}),
	"field_custom_status": msg({id: 'netrcol.application_settings.logCatalog.field_custom_status', message: "Custom status"}),
	"field_self_mute": msg({id: 'netrcol.application_settings.logCatalog.field_self_mute', message: "Mute"}),
	"field_self_deaf": msg({id: 'netrcol.application_settings.logCatalog.field_self_deaf', message: "Deafen"}),
	"field_self_video": msg({id: 'netrcol.application_settings.logCatalog.field_self_video', message: "Video"}),
	"field_self_stream": msg({id: 'netrcol.application_settings.logCatalog.field_self_stream', message: "Screen share"}),
	"field_suppress": msg({id: 'netrcol.application_settings.logCatalog.field_suppress', message: "Suppressed"}),
	"field_count": msg({id: 'netrcol.application_settings.logCatalog.field_count', message: "Messages"}),
	"field_channel": msg({id: 'netrcol.application_settings.logCatalog.field_channel', message: "Channel"}),
	"field_author_id": msg({id: 'netrcol.application_settings.logCatalog.field_author_id', message: "Author"}),
	"field_user_id": msg({id: 'netrcol.application_settings.logCatalog.field_user_id', message: "User"}),
	"field_emoji": msg({id: 'netrcol.application_settings.logCatalog.field_emoji', message: "Emoji"}),
	"field_code": msg({id: 'netrcol.application_settings.logCatalog.field_code', message: "Invite code"}),
	"field_duration_ms": msg({id: 'netrcol.application_settings.logCatalog.field_duration_ms', message: "Duration"}),
	"field_content_type": msg({id: 'netrcol.application_settings.logCatalog.field_content_type', message: "File format"}),
	"field_test": msg({id: 'netrcol.application_settings.logCatalog.field_test', message: "Test message"}),
	"field_banner_width": msg({id: 'netrcol.application_settings.logCatalog.field_banner_width', message: "Width"}),
	"field_banner_height": msg({id: 'netrcol.application_settings.logCatalog.field_banner_height', message: "Height"}),
	"field_splash_width": msg({id: 'netrcol.application_settings.logCatalog.field_splash_width', message: "Width"}),
	"field_splash_height": msg({id: 'netrcol.application_settings.logCatalog.field_splash_height', message: "Height"}),
	"field_splash_card_alignment": msg({id: 'netrcol.application_settings.logCatalog.field_splash_card_alignment', message: "Invite card alignment"}),
	"field_embed_splash_width": msg({id: 'netrcol.application_settings.logCatalog.field_embed_splash_width', message: "Width"}),
	"field_embed_splash_height": msg({id: 'netrcol.application_settings.logCatalog.field_embed_splash_height', message: "Height"}),
	"field_mfa_level": msg({id: 'netrcol.application_settings.logCatalog.field_mfa_level', message: "Two-factor authentication"}),
	"field_nsfw_level": msg({id: 'netrcol.application_settings.logCatalog.field_nsfw_level', message: "Mature content"}),
	"field_content_warning_level": msg({id: 'netrcol.application_settings.logCatalog.field_content_warning_level', message: "Content warning"}),
	"field_content_warning_text": msg({id: 'netrcol.application_settings.logCatalog.field_content_warning_text', message: "Content warning"}),
	"field_rules_channel_id": msg({id: 'netrcol.application_settings.logCatalog.field_rules_channel_id', message: "Rules channel"}),
	"field_member_count": msg({id: 'netrcol.application_settings.logCatalog.field_member_count', message: "Members"}),
	"field_message_history_cutoff": msg({id: 'netrcol.application_settings.logCatalog.field_message_history_cutoff', message: "Message history cutoff"}),
	"field_emoji_id": msg({id: 'netrcol.application_settings.logCatalog.field_emoji_id', message: "Emoji"}),
	"field_sticker_id": msg({id: 'netrcol.application_settings.logCatalog.field_sticker_id', message: "Stickers"}),
	"field_previous_attachments": msg({id: 'netrcol.application_settings.logCatalog.field_previous_attachments', message: "Attachments"}),
	"unavailable": msg({id: 'netrcol.application_settings.logCatalog.unavailable', message: "Fluxer does not produce this event yet."}),
	"scope": msg({id: 'netrcol.application_settings.logCatalog.scope', message: "Includes bots and private community channels."}),
	"privacy": msg({id: 'netrcol.application_settings.logCatalog.privacy', message: "Copied message text is visible to everyone who can read the log channel. Source files are not archived."}),
	"changed": msg({id: 'netrcol.application_settings.logCatalog.changed', message: "Changed"}),
};
